### ISSUE TITLE
Negative zero in floating-point constant table

### ISSUE THREAD

**Issue by minoki** [esumii/min-caml#13]
In `virtual.ml`, an entry in floating-point constant table is reused if they equate by `=`. Unfortunately, `=` does not distinguish the sign of zero, so MinCaml wrongly convert `-0.0` to `0.0` (or vice versa) if both `0.0` and `-0.0` are used in the program.

For example, the following code prints `0` on OCaml, but it will print `1` on MinCaml (I haven't managed to run the generated code, but the constant table in the assembly contains only `0.0`).

```ocaml
let rec f x = x /. 0.0 = x /. -0.0 in
if f (cos 0.0) then print_int 1 else print_int 0
```

In OCaml, there is [`Float.sign_bit`](https://v2.ocaml.org/api/Float.html#VALsign_bit) to examine the sign of zero, but it is a relatively new feature (since 4.08.0). Another solution is `d = d' && 1.0 /. d = 1.0 /. d'`.

**Comment by esumii** [comment]
Thanks for the report.  It sounds like a case where different "equalities" for floating-point numbers matter.  I wonder if 0.0 and -0.0 are the only example.  Any idea?

**Comment by esumii** [comment]
(Sorry for the mistake due to the UI of GitHub...!)

**Comment by minoki** [comment]
Yes, `0.0` and `-0.0` are the only ones that we need to care.

As for NaN, current (and proposed) code will produce multiple NaNs in the table, but it should be harmless.

**Comment by esumii** [comment]
My question may be why they are "the only ones that we need to care", or, why one wants MinCaml to distinguish 0.0 and -0.0 while OCaml "equates" (by = and other comparisons) them.  What is the general (rather than ad hoc) criterion here?

**Comment by minoki** [comment]
There are several notions of equality on IEEE floats. To name a few:

* The usual equality operator (IEEE compareQuietEqual): does not distinguish 0.0 and -0.0, and a NaN is not equal to itself.
* ECMAScript SameValue algorithm: distinguish 0.0 and -0.0 and all NaNs are equal.
* Bitwise equality: distinguish 0.0 and -0.0 and two NaNs are only equal if the sign, signaling-ness, and payload are equal.

Which equality should a compiler use? As a general rule, a compiler can replace a value with another if they behave identically.

There are some functions (e.g. reciprocal, atan2, `prerr_float`) that behave differently on 0.0 and -0.0, so the usual equality is not appropriate for a compiler. An equality which distinguish 0.0 and -0.0 should be used.

(As for NaN, some obscure functions (e.g. `sign_bit`) may behave differently on different NaNs, but a compiler may opt to ignore them. In fact, there are many compilers that does not distinguish signaling NaN and quiet NaN.)

I understand MinCaml puts emphasis on simplicity. Nevertheless, I think the change needed to distinguish 0.0 and -0.0 is small enough, and it may be instructive for a reader/student -- equality on floating-point numbers is not so simple!

**Comment by esumii** [comment]
I still do not see a consistent, logical reason why MinCaml should treat 0.0 and -0.0 as a special case to distinguish them (while different NaNs are "OK") while they are equated by =.  To me, it seems to be an ad hoc problem (and "solution") as a side artifact of IEEE float, which would be relevant in more realistic compilers but not a primary concern for MinCaml.  For pedagogy, I've added a link to this issue as comments in the source:
https://github.com/esumii/min-caml/commit/d06383e9ee1fb61c38d1359954fb788ea62402dd
Many thanks for the report and information!
