### ISSUE TITLE
License

### ISSUE THREAD

**Issue by curiousleo** [esumii/min-caml#14]
Hi! MinCaml is such a wonderful project, I keep coming back to it.

Would you consider adding a license to the project (or releasing it into the public domain, whichever you prefer)?

That would make it easier to contribute / fork and experiment / derive projects from the existing code: https://choosealicense.com/no-permission/

**Comment by esumii** [comment]
There is a LICENSE file.  I have just updated its timestamp.  https://github.com/esumii/min-caml/commit/f28d56843a030b7facf338fc59452494a60086ae

**Comment by curiousleo** [comment]
I can't fathom how I can possibly have missed that. I'm sorry for wasting your time with this issue!
