### ISSUE TITLE
Compile error caused by "Module_linked_twice"

### ISSUE THREAD

**Issue by KenSakayori** [esumii/min-caml#18]
MinCaml cannot be compiled using newer versions of OCaml (e.g. OCaml 5.1.0).

This is because MinCaml and OCaml compiler-libs both define modules named Parser and Lexer.
These name collisions were previously reported as warnings, but now these collisions are reported as errors.
(See https://github.com/ocaml/ocaml/pull/11635)
Probably, the easiest fix is to change the names of lexer.mll and parser.mly. 
Do you have any opinion on how this should be fixed?

**Comment by nojb** [comment]
Incidentally, this is only an issue if you are interested in the toplevel (`make min-caml.top`). The compiler itself does not link with compiler-libs (`make min-caml`).

**Comment by KenSakayori** [comment]
@nojb You are absolutely right. Good catch! (Both on my incorrect explanation and this issue itself.) I guess a better fix is to just remove `top` from the dependencies of `default` and `$(RESULT)` unless there's a strong reason for keeping the toplevel. (Although I've used this project for several years I never used it through REPL, but it might just be me.)

**Comment by esumii** [comment]
Thanks for the report!  Either solution seems good to me.  In the first case, we may rename the modules to simple names like myLexer.mll and myParser.mly.  (Sorry I don't have time to work on it right now...)

**Comment by esumii** [comment]
I've applied the minimal tentative workaround (removing "top" from Makefile): https://github.com/esumii/min-caml/commit/c08ffc5aee254f8c62aa572cfbe079fb102b44a8

I'll work on the more essential fix (change the modules names to MyLexer and MyParser) if I have time (or pull requests are welcome!).

**Comment by esumii** [comment]
Actually, I found it easier to do it now!
https://github.com/esumii/min-caml/commit/0410b6c775eb5251d5710283892a104adc5b2c9b
