### ISSUE TITLE
Type inference fails when applying function contains its callee in parameter

### ISSUE THREAD

**Issue by rhysd** [esumii/min-caml#4]
Repro:

```ml
let rec f _ = 42 in
print_int (f f)
```

Error:

```
uninstantiated type variable detected; assuming int
Fatal error: exception Typing.Error(_, 2, _)
```

It looks that type inference cannot infer the type of a function which is called with itself as argument such as `f` in above. But I'm not sure that this is a limitation of type inference. So I created this issue.

**Comment by nojb** [comment]
The type inferred for `f` is cyclic (in OCaml notation: `'a -> 'b as 'a`).  I do not think the `min-caml` type inference engine supports such types.

**Comment by nojb** [comment]
Of course, in your example, `'b = int`, so the type of `f` is `'a -> int as 'a`.

**Comment by rhysd** [comment]
yeah, occur check found that a parameter of function type refers the function itself. I noticed this while trying writing fixed point combinator like Y combinator or Z combinator. It contains the function `(g g)` where `g` is a function. So min-caml cannot represent fixed point combinator if the type of parameter cannot be inferred from elsewhere, is this correct?

**Comment by nojb** [comment]
I think so, yeah.  Note that the same is true of OCaml if you do not pass the `-rectypes` option.

**Comment by rhysd** [comment]
I see. Thank you for quick and clear answer. It was helpful :smile:

**Comment by esumii** [comment]
Right, MinCaml doesn't support recursive types (that can perhaps be a good exercise).  Thanks for the replies!
