### ISSUE TITLE
The type system is not polymorphic (missing generalization)

### ISSUE THREAD

**Issue by LPTK** [esumii/min-caml#8]
The [readme states](http://esumii.github.io/min-caml/index-e.html):

> As in ordinary ML, MinCaml infers the types of variables and functions even if no types are given in the program. This functionality is called type inference. It is very useful in particular for programs with polymorphic and higher-order functions.

But generalization and instantiation are missing from the type system, so it's not actually implementing polymorphic functions at all. For example, this fails:

```ocaml
let rec f y = 0 in
let _ = f 0 in
let _ = f true in
print_int 0
```

with:

```
Fatal error: exception Typing.Error(_, 2, 1)
```

If this is intended, it would be good to specify that the type system does actually not support Hindley-Milner type inference.

**Comment by FranklinChen** [comment]
The paper https://esumii.github.io/min-caml/paper.pdf explicitly says

```text
We present a simple compiler, consisting of only 2000 lines of ML,
for a strict, impure, monomorphic, and higher-order functional lan-
guage.
```

I guess the Git repo's README could have included this information.

**Comment by LPTK** [comment]
Yes, it would be nice to say it early on. It would spare the time spent looking at this project for someone who is interested in studying polymorphism (which is the _essence_ of ML and derivatives). Otherwise the project is nice, though!

**Comment by esumii** [comment]
The document you cited is not "readme" but a rather rough translation as warned in its first part:

> [Caution: This English tutorial is a tentative translation from the Japanese version and may still have many rough edges, both technically and linguistically. The academic paper is more complete.]

That said, the English sentence about type inference was indeed misleading, which is fixed now.  Thanks!
